"""BRAIN-matched alpha configuration for QuantConnect Cloud Python projects."""
CONFIG = {'alpha_id': 'levWKewl',
 'alpha_name': 'Estimate-Link × Certainty × IV180 Sector Hybrid',
 'paper': {'allowed_ports': [7497, 4002],
           'max_gross_notional': 100000,
           'max_name_notional': 5000,
           'max_order_notional': 5000,
           'max_orders': 100,
           'max_signal_age_calendar_days': 4,
           'min_order_notional': 25},
 'portfolio': {'gross_target': 1.0, 'max_abs_weight': 0.06, 'min_names': 20},
 'research': {'adv20_mode': 'auto',
              'capacity_capital': 1000000.0,
              'cost_bps_per_dollar_traded': 10.0,
              'financing_bps_annual': 0.0,
              'gap_policy': 'reset',
              'max_adv_participation': 0.01,
              'price_policy': 'error',
              'short_borrow_bps_annual': 0.0},
 'signal': {'certainty_weight': 0.2,
            'certainty_window': 84,
            'core_decay': 4,
            'core_final_weight': 0.65,
            'corr_window': 22,
            'est_backfill': 150,
            'iv_backfill': 55,
            'iv_mean': 32,
            'iv_weight': 0.2,
            'link_weight': 0.6,
            'platform_decay': 5,
            'range_decay': 5,
            'range_final_weight': 0.35,
            'stable_decay': 7,
            'volume_gate': 0.85},
 'timing': {'delay_days': 1, 'warmup_days_recommended': 200}}
